/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Controlador;
import modelo.Customers;

/**
 *
 * @author brand
 */
public class Page2 extends javax.swing.JPanel {

    /**
     * Creates new form Page2
     */
    
    Controlador objetocontrolador;
    public Page2() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_name = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_province = new javax.swing.JLabel();
        label_lastname = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_canton = new javax.swing.JLabel();
        label_birth = new javax.swing.JLabel();
        label_district = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        cus_lastname = new javax.swing.JTextField();
        cus_phone = new javax.swing.JTextField();
        cus_email = new javax.swing.JTextField();
        cus_birth = new javax.swing.JTextField();
        cus_canton = new javax.swing.JComboBox<>();
        cus_province = new javax.swing.JComboBox<>();
        cus_district = new javax.swing.JComboBox<>();
        regis = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(450, 270));

        label_name.setText("Nombre");

        label_phone.setText("Teléfono");

        label_province.setText("Provincia");

        label_lastname.setText("Apellido");

        label_email.setText("Correo");

        label_canton.setText("Catón");

        label_birth.setText("Fecha de nacimiento");

        label_district.setText("Distrito");

        cus_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_nameActionPerformed(evt);
            }
        });

        cus_canton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Ramón", " " }));

        cus_province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alajuela", "San José" }));
        cus_province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_provinceActionPerformed(evt);
            }
        });

        cus_district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peñas Blancas", " " }));

        regis.setText("Registar");
        regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_name)
                    .addComponent(label_phone)
                    .addComponent(label_province)
                    .addComponent(cus_name)
                    .addComponent(cus_province, 0, 157, Short.MAX_VALUE)
                    .addComponent(cus_district, 0, 157, Short.MAX_VALUE)
                    .addComponent(label_district)
                    .addComponent(cus_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cus_canton, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_lastname)
                    .addComponent(label_email)
                    .addComponent(label_canton)
                    .addComponent(cus_email, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(cus_lastname)
                    .addComponent(label_birth)
                    .addComponent(cus_birth))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regis)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_lastname)
                    .addComponent(label_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cus_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_email)
                    .addComponent(label_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cus_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cus_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_canton)
                    .addComponent(label_province))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cus_canton)
                    .addComponent(cus_province, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_district)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cus_district))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_birth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cus_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cus_provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_provinceActionPerformed
        
    }//GEN-LAST:event_cus_provinceActionPerformed

    private void regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisActionPerformed
       Customers cliente = new Customers ();
       cliente.setCostumer_code(1);
       cliente.setCostumer_name(cus_name.getText());
       cliente.setLast_namec(cus_lastname.getText());
       cliente.setPhone_number(Integer.valueOf(cus_phone.getText()));
       cliente.setCostumer_email(cus_email.getText());
       cliente.setCostumer_province((String) cus_province.getSelectedItem());
       cliente.setCostumer_canton((String) cus_canton.getSelectedItem());
       cliente.setCostumer_distict((String) cus_district.getSelectedItem());
       cliente.setBirth_date(Integer.valueOf(cus_birth.getText()));
       
       System.out.println(cliente.toString());
       
       
    }//GEN-LAST:event_regisActionPerformed
    
    
    public String getcus_name(){
        return cus_name.getText();
    }
    public String getcus_lastname(){
        return cus_lastname.getText();
    }
    public Integer getcus_phone(){
        return Integer.parseInt(cus_phone.getText());
    }
    public String getcus_email(){
        return cus_email.getText();
    }
    public String getcus_province(){
        return (String) cus_province.getSelectedItem();
    }
    public String getcus_canton(){
        return (String) cus_canton.getSelectedItem();
    }
    public String getcus_district(){
        return (String) cus_district.getSelectedItem();
    }
    public Integer getcus_birth(){
        return Integer.parseInt(cus_birth.getText());
    }
    
    
    private void cus_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cus_birth;
    public javax.swing.JComboBox<String> cus_canton;
    public javax.swing.JComboBox<String> cus_district;
    public javax.swing.JTextField cus_email;
    public javax.swing.JTextField cus_lastname;
    public javax.swing.JTextField cus_name;
    public javax.swing.JTextField cus_phone;
    public javax.swing.JComboBox<String> cus_province;
    private javax.swing.JLabel label_birth;
    private javax.swing.JLabel label_canton;
    private javax.swing.JLabel label_district;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_lastname;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_province;
    public javax.swing.JButton regis;
    // End of variables declaration//GEN-END:variables
}
